version = 0.1

[default.deploy.parameters]
stack_name = "smartpark"
resolve_s3 = true
s3_prefix = "smartpark"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"us.anthropic.claude-haiku-4-5-20251001-v1:0\" ParkingBufferMinutes=\"5\" CorsAllowOrigin=\"*\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
